# Generated by Django 5.0.3 on 2024-04-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_questions', '0002_xlexquestionmodel_indexable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xlexquestionmodel',
            name='meta_description',
            field=models.TextField(max_length=160),
        ),
    ]
