# Generated by Django 5.0.3 on 2024-03-15 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_modelos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsmodel',
            old_name='content',
            new_name='content_doc',
        ),
    ]
