# Generated by Django 5.0.3 on 2024-04-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_modelos', '0002_rename_content_documentsmodel_content_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsmodel',
            name='document',
        ),
    ]
