# Generated by Django 5.0.3 on 2024-04-12 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_modelos', '0003_remove_documentsmodel_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsmodel',
            name='ramo_direito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_modelos.ramodireitodocmodel'),
        ),
        migrations.AlterField(
            model_name='documentsmodel',
            name='tipo_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_modelos.tipodocumentmodel'),
        ),
    ]
