# Generated by Django 5.0.3 on 2024-04-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_modelos', '0004_alter_documentsmodel_ramo_direito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsmodel',
            name='indexable',
            field=models.BooleanField(default=True),
        ),
    ]
