# Generated by Django 5.0.3 on 2024-04-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sumulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumulamodel',
            name='indexable',
            field=models.BooleanField(default=True),
        ),
    ]
