# Generated by Django 5.0.3 on 2024-03-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesmodel',
            name='img_destaque',
        ),
        migrations.AddField(
            model_name='articlesmodel',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
