# Generated by Django 5.0.3 on 2024-03-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0002_remove_articlesmodel_img_destaque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='key_words',
            field=models.CharField(default='Artigos', max_length=255),
        ),
    ]
