# Generated by Django 5.0.3 on 2024-04-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0003_articlesmodel_key_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
