# Generated by Django 5.0.3 on 2024-04-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0004_articlesmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='indexable',
            field=models.BooleanField(default=True),
        ),
    ]
