# Generated by Django 5.0.3 on 2024-04-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesite',
            name='indexable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homesite',
            name='meta_title',
            field=models.CharField(default='Default Meta Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='homesite',
            name='meta_description',
            field=models.TextField(max_length=320),
        ),
        migrations.AlterField(
            model_name='homesite',
            name='site_description',
            field=models.TextField(),
        ),
    ]
