# Generated by Django 5.0.3 on 2024-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_homesite_indexable_homesite_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
