# Generated by Django 5.0.3 on 2024-03-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casos', '0002_alter_casoconcretomodel_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoconcretomodel',
            name='fundamentacao',
            field=models.TextField(blank=True, default='Fundamentação', null=True),
        ),
    ]
