# Generated by Django 5.0.3 on 2024-04-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casos', '0003_alter_casoconcretomodel_fundamentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoconcretomodel',
            name='indexable',
            field=models.BooleanField(default=True),
        ),
    ]
