# Generated by Django 5.0.3 on 2024-03-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principiosmodel',
            name='content',
        ),
        migrations.AddField(
            model_name='principiosmodel',
            name='content_principio',
            field=models.TextField(blank=True, default='Principio', null=True),
        ),
    ]
